name: Chromatic
description: Publish stories to Chromatic
inputs:
  frontend_directory:
    description: "The frontend source directory"
    required: true
  project_token:
    description: "The Chromatic project token"
    required: true
  pat:
    description: "The Github PAT"
    required: true

runs:
  using: "composite"

  steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR

      - uses: actions/setup-node@v3
        if: steps.PR.outputs.pr_found == 'true'
        with:
          node-version: 17
          cache: pnpm
          cache-dependency-path: ${{ inputs.frontend_directory }}

      - name: Install dependencies
        if: steps.PR.outputs.pr_found == 'true'
        run: pnpm install --frozen-lockfile
        working-directory: ${{ inputs.frontend_directory }}
        shell: bash

      - name: Publish to Chromatic
        if: steps.PR.outputs.pr_found == 'true'
        uses: chromaui/action@v1
        with:
          projectToken: ${{ inputs.project_token }}
          onlyChanged: "MON-**"
          workingDir: ${{ inputs.frontend_directory }}
          token: ${{ inputs.pat }}
          buildScriptName: build:storybook