name: "Publish Lighthouse report to S3"
description: "Publish Lighthouse report to S3"
inputs:
  report_path:
    description: "report_path"
    required: true
  report_target:
    description: "report_target"
    required: true
  access_key_id:
    description: "access_key_id"
    required: true
  secret_access_key:
    description: "secret_access_key"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
      with:
        python-version: "3.10"

    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@27d6061dae5d39e89be4d2246824f15e111a7e06
      with:
        version: 2
        verbose: false
        arch: amd64

    - name: "Setup AWS context"
      run: |
        if [[ "$GITHUB_REF_NAME" != "develop" && "$GITHUB_REF_NAME" != "master" ]]; then
          VERSION=$(echo $GITHUB_REF_NAME | grep -oE '([0-9]{2}\.[0-9]{2})').x
        else
          VERSION=$GITHUB_REF_NAME
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "AWS_ACCESS_KEY_ID=${{ inputs.access_key_id }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ inputs.secret_access_key }}" >> $GITHUB_ENV
      shell: bash

    - name: "Push report"
      run: aws s3 cp "${{ inputs.report_path }}" "${{ inputs.report_target }}${{ env.VERSION }}/index.html" --acl public-read --region eu-west-1
      shell: bash

    - name: "Clean up AWS credentials"
      run: |
        echo "AWS_ACCESS_KEY_ID=" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=" >> $GITHUB_ENV
      shell: bash
