name: "check-version"
description: "Compare current stable version with version from ref"
inputs:
  module_name:
    description: "The module name"
    required: true
  major_version:
    description: "The major version"
    required: true
  minor_version:
    description: "The minor version"
    required: true
  stability:
    description: "The stability"
    required: true

runs:
  using: "composite"
  steps:
  - id: check_version
    run: |
      set -eux

      # Make sure version is NOT the same as the current stable.
      # If it is, abort any job beyond this point

      CURRENT_STABLE_TAG=$(git tag -l 'centreon-${{ inputs.module_name }}-${{ inputs.major_version }}-${{ inputs.minor_version }}')
      CURRENT_STABLE_VERSION=$(git tag -l 'centreon-${{ inputs.module_name }}-${{ inputs.major_version }}-${{ inputs.minor_version }}' | awk -F '-' '{print $3}' )
      REF_VERSION="${{ inputs.major_version }}.${{ inputs.minor_version }}"
      echo "Current stable tag is: $CURRENT_STABLE_TAG"
      echo "Current stable version is: $CURRENT_STABLE_VERSION"

      # Compare current stable version with ref version

      if [[ "$CURRENT_STABLE_VERSION" == "$REF_VERSION" ]];then
        echo "Current stable version is the same as version of this branch, action required, aborting."
        exit 1
      elif [[ "$CURRENT_STABLE_VERSION" -lt "$REF_VERSION" ]]
        echo "Current stable version is lesser than branch version."
      else
        echo "Invalid version."
      fi

    shell: bash

