name: "Web Cypress Component Testing"
description: "Web Cypress Component Testing"
inputs:
  module:
    description: "Module on which the test will be run"
    required: true
  prepath:
    description: "Path preceding the spec_file_path"
    required: true
  spec_file_path:
    description: "Path of spec file."
    required: true

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 7

    - uses: mad9000/actions-find-and-replace-string@2
      id: formatSpecFilePath
      with:
          source: ${{ inputs.spec_file_path }}
          find: '.cypress.spec.tsx'
          replace: ''
          
    - name: LS
      run: |
        ls
        echo ${{ inputs.spec_file_path }}
        echo ${{ inputs.prepath }}
        echo ${{ inputs.module }}
      shell: bash

    - name: Cypress web component testing
      uses: cypress-io/github-action@v5
      with:
        browser: chrome
        component: true
        install-command: pnpm install
        working-directory: ${{ inputs.module }}
        spec: ${{ inputs.prepath }}${{ inputs.spec_file_path }}
        publish-summary: false

    - name: Archive videos
      uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        name: cypress-videos-${{ steps.formatSpecFilePath.outputs.value }}
        path: ${{ inputs.module }}/cypress/results/videos
        retention-days: 1

    - name: Archive screenshots
      uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        name: cypress-screenshots-${{ steps.formatSpecFilePath.outputs.value }}
        path: ${{ inputs.module }}/cypress/screenshots
        retention-days: 1
    
    - name: Archive snapshots
      uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        name: cypress-snapshots-${{ steps.formatSpecFilePath.outputs.value }}
        path: ${{ inputs.module }}/cypress/visual-testing-snapshots
        retention-days: 1
