name: "Web Cypress Component Testing"
description: "Web Cypress Component Testing"
inputs:
  module:
    description: "Module on which the test will be run"
    required: true
  spec_file_path:
    description: "Path of spec file."
    required: true
  dependencies_lock_file:
    description: "The frontend dependencies lock file path"
    required: true

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false

    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: pnpm
        cache-dependency-path: ${{ inputs.dependencies_lock_file }}

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      working-directory: ${{ inputs.module }}
      shell: bash
      env:
        CYPRESS_INSTALL_BINARY: "0"
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"

    - name: Install Cypress binary
      uses: nick-fields/retry@v2
      with:
        timeout_seconds: 120
        max_attempts: 10
        retry_wait_seconds: 30
        retry_on: error
        command: cd ${{ inputs.module }} && pnpm cypress install --force

    - name: Install browser dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq -y install wget libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb xdg-utils libu2f-udev fonts-liberation libu2f-udev fonts-liberation xdg-utils
        sudo wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.90-1_amd64.deb
        sudo apt-get install -y ./google-chrome-stable_114.0.5735.90-1_amd64.deb
        sudo dpkg -i google-chrome-stable_114.0.5735.90-1_amd64.deb
      shell: bash

    - name: Cypress web component testing
      uses: cypress-io/github-action@v5
      with:
        browser: chrome
        component: true
        install: false
        cache-key: cypress-cache-${{ runner.os }}-${{ hashFiles(inputs.dependencies_lock_file) }}
        working-directory: ${{ inputs.module }}
        spec: ${{ inputs.spec_file_path }}
        publish-summary: false
        env: codeCoverageTasksRegistered=true

    - name: Archive test results
      uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        name: component-test-results
        path: |
          ${{ inputs.module }}/cypress/results/videos
          ${{ inputs.module }}/cypress/screenshots
          ${{ inputs.module }}/cypress/visual-testing-snapshots
        retention-days: 1
