name: centreon-js-config

on:
  pull_request:
    paths:
      - ".github/workflows/js-config.yml"
      - "centreon/packages/js-config/**"
      - "centreon/.github/actions/npm-publish-package/**"
    branches:
      - develop

env:
  directory: "centreon/packages/js-config"
  centreon_directory: "centreon"
  package: 'js-config'
  base_branch: develop

jobs:
  deliver-npm:
    runs-on: ubuntu-22.04
    needs: check-package-version

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.CENTREON_TECHNIQUE_TOKEN }}

      - uses: ./.github/actions/npm-publish-package
        with:
          directory: ${{ env.directory }}
          pat: ${{ secrets.CENTREON_TECHNIQUE_TOKEN }}
          npm_token: ${{ secrets.NPM_TOKEN }}
          release_branch: ${{ env.base_branch }}
          package: ${{ env.package }}
          release_type: "beta"

  check-package-version:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/check-package-version
        with:
          base_branch: ${{ env.base_branch }}
          directory: ${{ env.directory }}
