---
name: Centreon Workflow

on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_version:
        required: true
        type: string

jobs:
  test:
    runs-on: self-hosted
    name: Test ${{ inputs.module_name }}-${{ inputs.image_name }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Testing ${{ inputs.module_name }} ${{ inputs.image_name }}
        run: docker run -i --entrypoint /src/ci/scripts/${{ inputs.module_name }}-test-${{ inputs.image_name }}.sh -v "$PWD:/src" registry.centreon.com/${{ inputs.module_name }}-build-${{ inputs.image_name }}:${{ inputs.image_version }}

  build:
    runs-on: self-hosted
    name: Build ${{ inputs.module_name }}-${{ inputs.package }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Building ${{ inputs.module_name }} ${{ inputs.package }}
        run: docker run -i --entrypoint /src/ci/scripts/${{ inputs.module_name }}-build-${{ inputs.package }}.sh -v "$PWD:/src" registry.centreon.com/${{ inputs.module_name }}-build-${{ inputs.package }}:${{ inputs.docker_version }}

  package:
    runs-on: self-hosted
    name: Package
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Package LM
        run: docker run -i --entrypoint /src/ci/scripts/${{ inputs.module_name }}-packaging.sh -v "$PWD:/src" registry.centreon.com/${{ inputs.module_name }}-package:1.3

      - name: Use cache RPM files
        uses: actions/cache@v3
        env:
          cache-name-rpmbuild: cache-${{ github.sha }}-${{ github.run_id }}-rpmbuild
        with:
          path: ./*.rpm
          key: ${{ env.cache-name-rpmbuild }}

  dockerise:
    needs: [package, test, build]
    runs-on: self-hosted
    name: Dockerise
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Use cache RPM files
        uses: actions/cache@v3
        env:
          cache-name-rpmbuild: cache-${{ github.sha }}-${{ github.run_id }}-rpmbuild
        with:
          path: ./*.rpm
          key: ${{ env.cache-name-rpmbuild }}

      - name: Dockerise ${{ inputs.module_name }}
        run: ./ci/scripts/dockerise-${{ inputs.module_name }}.sh

  delivery:
    needs: dockerise
    runs-on: self-hosted
    name: Delivery
    steps:
      - name: Use cache RPM files
        uses: actions/cache@v3
        env:
          cache-name-rpmbuild: cache-${{ github.sha }}-${{ github.run_id }}-rpmbuild
        with:
          path: ./*.rpm
          key: ${{ env.cache-name-rpmbuild }}

      - name: Publish RPMS to Nexus
        run: |
          for FILE in *.rpm;
          do
            curl -v -u ${{ secrets.NEXUS_RPMS_REPOSITORY_USERNAME }}:${{ secrets.NEXUS_RPMS_REPOSITORY_PASSWORD }} --upload-file ./$FILE 'http://nexus-service.software-factory.svc.cluster.local:8081/repository/rpm-releases/'
          done