name: Postman Tests

on:
  push:

jobs:
  postman_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: centreon/tests/rest_api
        
    env:
      CONTAINER_NAME: my_centreon_container
      CENTREON_URL: http://localhost
      CENTREON_IMAGE: docker.centreon.com/centreon/centreon-web-alma9:develop

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_ID }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}
      
      - name: Install pnpm
        run: npm install pnpm -g

      - name: Install Dependencies
        run: pnpm install -f ./centreon/tests/rest_api/package.json

      - name: Start Centreon Web Container
        run: docker run --name $CONTAINER_NAME -d -p 4000:80 --health-cmd="curl -f $CENTREON_URL/ || exit 1" --health-interval=5s $CENTREON_IMAGE

      - name: Wait for Centreon Web Container to Start
        run: |
          npx wait-on http://localhost:4000/ --timeout 100000
        timeout-minutes: 5
      
      - name: List contents of node_modules
        run: |
          ls -lR node_modules

      - name: Run Postman Tests and Generate HTML Report
        run: |
          environment_path="collections/Environment-for-Refactored-API-Test-Collection.json"
          collection_path="collections"

          # Create a directory to store HTML reports
          mkdir -p newman

          # Define an array to store execution information
          executions=()

          # Iterate over each Postman collection file in the specified directory
          for collection_file in "$collection_path"/*.postman_collection.json; do
            # Extract the collection name from the file name
            collection_name=$(basename "$collection_file" .postman_collection.json)

            # Run Newman with the current collection file and generate an HTML report
            pnpm newman run "$collection_file" -e "$environment_path" --reporters cli,htmlextra --reporter-htmlextra-title "$collection_name" --reporter-htmlextra-title "${collection_name// /_}" --reporter-htmlextra-export "newman/${collection_name}.html"  || true

            # Store execution information in the array
            executions+=("{\"collectionName\":\"$collection_name\", \"collectionUrl\":\"collections/$collection_name.postman_collection.json\", \"reportName\":\"$collection_name.html\", \"reportUrl\":\"newman/$collection_name.html\"}")
          done

          # Convert the executions array to a JSON string
          executionsJson="[$(IFS=,; echo "${executions[*]}")]"

          # Inject the executions JSON into the custom HTML template
          echo "$executionsJson" > executions.json
        working-directory: centreon/tests/rest_api  

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v2
        with:
          name: postman-html-reports
          path: centreon/tests/rest_api/newman/
        env:
          NODE_VERSION: 16

      - name: Create Custom Summary HTML
        run: |
          cat > custom-summary.html <<EOF
          <!DOCTYPE html>
          <html>
          <head>
              <title>Custom Summary Report</title>
          </head>
          <body>
              <h1>Custom Summary Report</h1>
              <table border="1">
                  <tr>
                      <th>Collection</th>
                      <th>Report</th>
                  </tr>
                  {{#executions}}
                  <tr>
                      <td><a href="{{collectionUrl}}">{{collectionName}}</a></td>
                      <td><a href="{{reportUrl}}">{{reportName}}</a></td>
                  </tr>
                  {{/executions}}
              </table>
          </body>
          </html>
          EOF
        working-directory: centreon/tests/rest_api

      - name: Upload Custom Summary HTML
        uses: actions/upload-artifact@v2
        with:
          name: custom-summary-html
          path: centreon/tests/rest_api/custom-summary.html

      - name: Continue to Next Collection
        if: ${{ always() }}
        run: echo "Continuing to the next collection..."
