name: Postman Tests

on:
  push:

jobs:
  postman_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: centreon/tests/rest_api

    env:
      CONTAINER_NAME: my_centreon_container
      CENTREON_URL: http://localhost
      CENTREON_IMAGE: docker.centreon.com/centreon/centreon-web-alma9:develop

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_ID }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}

      - name: Install pnpm
        run: npm install pnpm -g

      - name: Install Dependencies
        run: pnpm install -f ./centreon/tests/rest_api/package.json

      - name: Start Centreon Web Container
        run: docker run --name $CONTAINER_NAME -d -p 4000:80 --health-cmd="curl -f $CENTREON_URL/ || exit 1" --health-interval=5s $CENTREON_IMAGE

      - name: Wait for Centreon Web Container to Start
        run: |
          npx wait-on http://localhost:4000/ --timeout 100000
        timeout-minutes: 5

      - name: List contents of node_modules
        run: |
          ls -lR node_modules

      - name: Run Postman Tests and Generate HTML and JSON Reports
        run: |
          environment_path="collections/Environment-for-Refactored-API-Test-Collection.json"
          collection_path="collections"

          # Create necessary directories
          mkdir -p centreon/tests/rest_api/newman
          mkdir -p centreon/tests/rest_api/newman/json-summary
          
          # List files in JSON summary directory
          ls -lR centreon/tests/rest_api/newman/json-summary

          # Iterate over each Postman collection file in the specified directory
          for collection_file in "$collection_path"/*.postman_collection.json; do
            # Extract the collection name from the file name
            collection_name=$(basename "$collection_file" .postman_collection.json)

            # Run Newman with the current collection file and generate HTML and JSON reports
            pnpm newman run "$collection_file" -e "$environment_path" -r cli,htmlextra,json,json-summary --reporter-htmlextra-title "${collection_name// /_}" --reporter-htmlextra-export "centreon/tests/rest_api/newman/${collection_name}.html" --reporter-json-export "centreon/tests/rest_api/newman/${collection_name}.json" --reporter-summary-json-export "centreon/tests/rest_api/newman/json-summary/${collection_name}-summary.json" || true
          done     

          # List files in JSON summary directory again
          ls -lR centreon/tests/rest_api/newman/json-summary

      - name: Upload HTML and JSON Reports
        uses: actions/upload-artifact@v2
        with:
          name: postman-reports
          path: |
            centreon/tests/rest_api/newman/
        env:
          NODE_VERSION: 16

      - name: Extract and Store Summaries
        run: |
          summaries=""
          for summary_file in centreon/tests/rest_api/newman/json-summary/*.json; do
            collection_name=$(basename "$summary_file" -summary.json)
            summary_content=$(cat "$summary_file" | jq -c '.["collection"]["info"]["name"], .["run"]["stats"]["requests"]["total"], .["run"]["stats"]["requests"]["pending"], .["run"]["stats"]["requests"]["failed"], .["run"]["stats"]["assertions"]["total"], .["run"]["stats"]["assertions"]["pending"], .["run"]["stats"]["assertions"]["failed"]')
            summaries="$summaries\"$collection_name\": $summary_content,"
          done
          summaries="${summaries%,}" # Remove the trailing comma
          echo "GITHUB_STEP_SUMMARIES={$summaries}" >> $GITHUB_ENV

      - name: Continue to Next Collection
        if: ${{ always() }}
        run: echo "Continuing to the next collection..."

      - name: Display Newman Reports Summary
        run: echo "## Newman Reports Summary\n\n${{ env.newman_reports_summary }}" >> $GITHUB_ENV
