name: Postman Tests

on:
  push:

jobs:
  postman_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: centreon/tests/rest_api

    env:
      CONTAINER_NAME: my_centreon_container
      CENTREON_URL: http://localhost
      CENTREON_IMAGE: docker.centreon.com/centreon/centreon-web-alma9:develop

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_ID }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}

      - name: Install pnpm
        run: npm install pnpm -g

      - name: Install Dependencies
        run: pnpm install -f ./centreon/tests/rest_api/package.json

      - name: Start Centreon Web Container
        run: docker run --name $CONTAINER_NAME -d -p 4000:80 --health-cmd="curl -f $CENTREON_URL/ || exit 1" --health-interval=5s $CENTREON_IMAGE

      - name: Wait for Centreon Web Container to Start
        run: |
          npx wait-on http://localhost:4000/ --timeout 100000
        timeout-minutes: 5

      - name: List contents of node_modules
        run: |
          ls -lR node_modules

      - name: Run Postman Tests and Generate Reports
        run: |
          environment_path="collections/Environment-for-Refactored-API-Test-Collection.json"
          collection_path="collections"
          report_directory="centreon/tests/rest_api/newman"

          # Create a directory to store reports
          mkdir -p "$report_directory"

          # Initialize variables to store test results
          tests_passed=0
          tests_failed=0
          tests_skipped=0

          # Iterate over each Postman collection file in the specified directory
          for collection_file in "$collection_path"/*.postman_collection.json; do
            # Extract the collection name from the file name
            collection_name=$(basename "$collection_file" .postman_collection.json)

            # Run Newman with the current collection file and generate HTML and JSON reports
            pnpm newman run "$collection_file" -e "$environment_path" --reporters cli,htmlextra,json --reporter-htmlextra-title "$collection_name" --reporter-htmlextra-title "${collection_name// /_}" --reporter-htmlextra-export "$report_directory/${collection_name}.html" --reporter-json-export "$report_directory/${collection_name}.json" || true

            # Extract test results from the JSON report and update variables
            current_results=$(jq -r '.run.stats.tests' "$report_directory/${collection_name}.json")
            current_passed=$(echo "$current_results" | jq -r '.passed')
            current_failed=$(echo "$current_results" | jq -r '.failed')
            current_skipped=$(echo "$current_results" | jq -r '.skipped')

            tests_passed=$((tests_passed + current_passed))
            tests_failed=$((tests_failed + current_failed))
            tests_skipped=$((tests_skipped + current_skipped))
          done

          echo "Tests Passed: $tests_passed"
          echo "Tests Failed: $tests_failed"
          echo "Tests Skipped: $tests_skipped"
        working-directory: centreon/tests/rest_api

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: postman-reports
          path: centreon/tests/rest_api/newman
        env:
          NODE_VERSION: 16

      - name: Create and Upload README Summary
        run: |
          echo "# Postman Tests Summary" > README.md
          echo "Tests Passed: $tests_passed" >> README.md
          echo "Tests Failed: $tests_failed" >> README.md
          echo "Tests Skipped: $tests_skipped" >> README.md

          # Upload README.md
          echo "::set-output name=readme-summary::README.md"
        shell: bash

      - name: Create GitHub Summary
        id: create-github-summary
        run: |
          # Your logic to create GitHub summary from test results
          # Use $tests_passed, $tests_failed, $tests_skipped to access test results
          summary="**Postman Tests Summary**\n\n"
          summary+="Tests Passed: $tests_passed\n"
          summary+="Tests Failed: $tests_failed\n"
          summary+="Tests Skipped: $tests_skipped\n"
 
          # Save the summary to a file
          echo -e "$summary" > postman_summary.md

          # Upload the summary as an artifact
          echo "::set-output name=github-summary::postman_summary.md"
        shell: bash

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v2
        with:
         name: postman-html-reports
         path: centreon/tests/rest_api/newman/
        env:
         NODE_VERSION: 16

      - name: Continue to Next Collection
        if: ${{ always() }}
        run: echo "Continuing to the next collection..."
