name: Postman Tests

on:
  push:
    # paths:
    #   - 'centreon/tests/rest_api/refactored_api_test_collection/**'

jobs:
  postman_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Install Newman and Reporter
        run: | 
          npm install -g newman newman-reporter-htmlextra newman-reporter-text
      
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_ID }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}

      - name : start centreon web container
        run: docker run -d -p 4000:80 docker.centreon.com/centreon/centreon-web-alma9:develop
      
      - name: Run Postman Tests and Generate HTML Report
        run: |
          environment_path="centreon/tests/rest_api/refactored_api_test_collection/Environment-for-Refactored-API-Test-Collection.json"
          collection_path="centreon/tests/rest_api/refactored_api_test_collection"

          # Nom de la collection à exécuter
          collection_name="10-Authentication-on-an-admin-account-Centreon-Web-Refactored-API-Test-Collection.postman_collection"

          # Create a directory to store HTML reports
          mkdir -p newman

          # Run Newman with the specified collection file and generate an HTML report
          newman run "$collection_path/$collection_name.postman_collection.json" -e "$environment_path" --reporters cli,htmlextra --reporter-htmlextra-title "$collection_name" --reporter-htmlextra-title "${collection_name// /_}" --reporter-htmlextra-export "newman/${collection_name}.html"
      - name: Upload HTML Reports
        uses: actions/upload-artifact@v2
        with:
          name: postman-html-reports
          path: ./newman/
