on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  notify-on-slack:
    runs-on: ubuntu-22.04
    steps:
      - uses: slackapi/slack-github-action@v1.23.0
        with:
          # Post a notification using rick message using Block Kit
          payload: |
            {
              "text": "Title: ${{ inputs.message }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Content: ${{ inputs.message }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
