---
name: release-widget-live-top10-memory-usage

on:
  pull_request_target:
    types:
      - closed
    branches:
      - master
      - "[2-9][0-9].[0-9][0-9].x"
    paths:
      - "widgets/centreon-widget-live-top10-memory-usage/**"
  workflow_dispatch:

env:
  module: "widget-live-top10-memory-usage"

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release
        id: release
        uses: ./.github/actions/release
        with:
          module_name: ${{ env.module }}
          jira_token: ${{ secrets.JIRA_TOKEN }}
