name: centreon-ui-context

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/ui.yml"
      - "centreon/packages/ui-context/**"
  push:
    branches:
      - dev-22.04.x
    paths:
      - ".github/workflows/ui.yml"
      - "centreon/packages/ui-context/**"
    tags-ignore:
      - ui-context-*

env:
  version: "22.04"
  directory: "centreon/packages/ui-context"
  centreon_directory: "centreon"

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ${{ env.centreon_directory }}

      - name: Lint
        run: npm run eslint -- -o checkstyle.xml -f checkstyle
        working-directory: ${{ env.directory }}

      - name: Publish report
        if: ${{ always() }}
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          name: centreon-ui-context-eslint-report
          path: ${{ env.directory }}/checkstyle.xml

  deliver-npm:
    runs-on: ubuntu-22.04
    needs: [lint]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Update JS config version
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          npm version patch -m "js-config-%s" --legacy-peer-deps
          VERSION=ui-context-$(node -p "require('./package.json').version")
          git tag ${VERSION}
          git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" origin/dev-22.04.x --follow-tags
          git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" origin/dev-22.04.x --tags
        working-directory: ${{ env.directory }}

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ${{ env.directory }}/package.json
          tag: ${{ github.head_ref || github.ref_name }}
          access: public