name: web

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "centreon/**"
      - "!centreon/packages/**"
      - "!centreon/.veracode-exclusions"
  push:
    branches:
      - develop
      - dev-[2-9][0-9].[0-9][0-9].x
      - master
      - "[2-9][0-9].[0-9][0-9].x"
    paths:
      - "centreon/**"
      - "!centreon/packages/**"
      - "!centreon/.veracode-exclusions"
    tags:
      - centreon-*

env:
  base_directory: centreon

jobs:
  changes:
    runs-on: ubuntu-22.04
    outputs:
      has_frontend_changes: ${{ steps.filter.outputs.has_frontend_changes }}
      has_backend_changes: ${{ steps.filter.outputs.has_backend_changes }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            has_frontend_changes:
              - '**/*.[jt]sx?'
              - '**/www/front_src/**'
              - '**/tests/e2e/**'
              - '**/package*'
              - '**/lighthouse/**'
              - '**/tsconfig.json'
              - '**/cypress/**|**/pnpm-*'
            has_backend_changes:
              - '**/*.php'
              - '**/phpstan*.neon'
              - 'centreon/codingstyle.xml'
              - 'centreon/config/**/*.xml'
              - 'centreon/phpunit.xml'
              - 'centreon/ruleset.xml'
              - 'centreon/www/**/*.xml'
              - '**/bin/**'
              - '**/tmpl/**'
              - '**/features/**'
              - '/centreon/src/**'
              - '**/config/**'
              - '**/composer.*'
              - '**/tests/api/**'
              - '**/tests/php/**'
              - '**/tests/clapi_export/**'
              - '**/www/!(front_src)/**'
              - '**/doc/API/**'
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  get-version:
    uses: ./.github/workflows/get-version.yml
    with:
      version_file: centreon/www/install/insertBaseConf.sql

  frontend-build:
    needs: [get-version]
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/frontend-build
        with:
          base_directory: ${{ env.base_directory }}
          index_file: ${{ env.base_directory }}/www/index.html
          static_directory: ${{ env.base_directory }}/www/static
          index_cache_key: ${{ github.sha }}-${{ github.run_id }}-index
          static_cache_key: ${{ github.sha }}-${{ github.run_id }}-static

  backend-dependencies:
    needs: [get-version]
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/backend-dependencies
        with:
          base_directory: ${{ env.base_directory }}
          cache_key: ${{ github.sha }}-${{ github.run_id }}-vendor

  translation-build:
    needs: [get-version]
    runs-on: ubuntu-22.04
    container:
      image: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/translation:${{ needs.get-version.outputs.major_version }}
      credentials:
        username: ${{ secrets.DOCKER_REGISTRY_ID }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}

    steps:
      - uses: actions/checkout@v3

      - run: |
          cd centreon
          mkdir -p www/locale/en_US.UTF-8/LC_MESSAGES
          php bin/centreon-translations.php en lang/fr_FR.UTF-8/LC_MESSAGES/messages.po www/locale/en_US.UTF-8/LC_MESSAGES/messages.ser
          for i in lang/* ; do
            localefull=`basename $i`
            langcode=`echo $localefull | cut -d _ -f 1`
            mkdir -p "www/locale/$localefull/LC_MESSAGES"
            msgfmt "lang/$localefull/LC_MESSAGES/messages.po" -o "www/locale/$localefull/LC_MESSAGES/messages.mo" || exit 1
            msgfmt "lang/$localefull/LC_MESSAGES/help.po" -o "www/locale/$localefull/LC_MESSAGES/help.mo" || exit 1
            php bin/centreon-translations.php "$langcode" "lang/$localefull/LC_MESSAGES/messages.po" "www/locale/$localefull/LC_MESSAGES/messages.ser"
          done
        shell: bash

      - uses: actions/cache@v3
        with:
          path: ${{ env.base_directory }}/www/locale
          key: ${{ github.sha }}-${{ github.run_id }}-translation

  package:
    needs:
      [
        get-version,
        translation-build,
        backend-dependencies,
        frontend-build,
      ]
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && needs.get-version.outputs.stability != 'stable' }}

    strategy:
      matrix:
        distrib: [el8, el9, bullseye]
        include:
          - package_extension: rpm
            image: packaging-alma8
            distrib: el8
          - package_extension: rpm
            image: packaging-alma9
            distrib: el9
          - package_extension: deb
            image: packaging-bullseye
            distrib: bullseye

    uses: ./.github/workflows/package.yml
    with:
      base_directory: centreon
      spec_file: centreon/packaging/centreon.spectemplate
      package_extension: ${{ matrix.package_extension }}
      frontend_index_cache_key: ${{ github.sha }}-${{ github.run_id }}-index
      frontend_index_file: centreon/www/index.html
      frontend_static_cache_key: ${{ github.sha }}-${{ github.run_id }}-static
      frontend_static_directory: centreon/www/static
      backend_vendor_cache_key: ${{ github.sha }}-${{ github.run_id }}-vendor
      backend_vendor_directory: centreon/vendor
      translation_cache_key: ${{ github.sha }}-${{ github.run_id }}-translation
      translation_directory: centreon/www/locale
      image_name: ${{ matrix.image }}
      module_name: centreon
      major_version: ${{ needs.get-version.outputs.major_version }}
      minor_version: ${{ needs.get-version.outputs.minor_version }}
      release: ${{ needs.get-version.outputs.release }}
      commit_hash: ${{ github.sha }}
      cache_key: ${{ github.sha }}-${{ github.run_id }}-${{ matrix.package_extension }}-${{ matrix.distrib }}
    secrets:
      registry_username: ${{ secrets.DOCKER_REGISTRY_ID }}
      registry_password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}

  dockerize:
    runs-on: ubuntu-22.04
    needs: [package, get-version]
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && needs.get-version.outputs.stability != 'stable' }}

    strategy:
      matrix:
        os: [alma9]
        include:
          - project: centreon-web
          - os: alma9
            distrib: el9
            package_extension: rpm

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_ID }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}

      - name: Restore ${{ matrix.package_extension }} files
        uses: actions/cache@v3
        with:
          path: ./*.${{ matrix.package_extension }}
          key: ${{ github.sha }}-${{ github.run_id }}-${{ matrix.package_extension }}-${{ matrix.distrib }}
          fail-on-cache-miss: true

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v3
        with:
          file: .github/docker/Dockerfile.${{ matrix.project }}-${{ matrix.os }}
          target: web_fresh
          context: .
          build-args: |
            "REGISTRY_URL=${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}"
            "VERSION=${{ needs.get-version.outputs.major_version }}"
          pull: true
          load: true
          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.project }}-fresh-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}

      - uses: docker/build-push-action@v3
        with:
          file: .github/docker/Dockerfile.${{ matrix.project }}-${{ matrix.os }}
          target: web_fresh
          context: .
          build-args: |
            "REGISTRY_URL=${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}"
            "VERSION=${{ needs.get-version.outputs.major_version }}"
          pull: false
          push: true
          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.project }}-fresh-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}

      - uses: docker/build-push-action@v3
        with:
          file: .github/docker/Dockerfile.${{ matrix.project }}-${{ matrix.os }}
          target: web_standard
          context: .
          build-args: |
            "REGISTRY_URL=${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}"
            "VERSION=${{ needs.get-version.outputs.major_version }}"
          pull: true
          load: true
          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.project }}-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}

      - uses: docker/build-push-action@v3
        with:
          file: .github/docker/Dockerfile.${{ matrix.project }}-${{ matrix.os }}
          target: web_standard
          context: .
          build-args: |
            "REGISTRY_URL=${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}"
            "VERSION=${{ needs.get-version.outputs.major_version }}"
          pull: false
          push: true
          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.project }}-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}

      - name: Setup docker slim
        run: |
          wget -q https://downloads.dockerslim.com/releases/1.40.0/dist_linux.tar.gz
          tar -xf dist_linux.tar.gz
          mv dist_linux/docker-slim /usr/local/bin/
          mv dist_linux/slim-sensor /usr/local/bin/
          mv dist_linux/slim /usr/local/bin/
        shell: bash

      - name: Build and push slim images
        run: |
          for IMAGE_SUFFIX in "" "-fresh"; do
            slim build --show-clogs --show-blogs \
              --include-shell \
              --http-probe-off \
              --exec-file .github/docker/slim-configuration/exec.txt \
              --include-path-file .github/docker/slim-configuration/include-path.txt \
              --include-bin-file .github/docker/slim-configuration/include-bin.txt \
              --path-perms-file .github/docker/slim-configuration/path-perms.txt \
              --tag ${{ matrix.project }}$IMAGE_SUFFIX-slim-${{ matrix.os }} \
              ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.project }}$IMAGE_SUFFIX-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}
            docker tag ${{ matrix.project }}$IMAGE_SUFFIX-slim-${{ matrix.os }} ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.project }}$IMAGE_SUFFIX-slim-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}
            docker push ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.project }}$IMAGE_SUFFIX-slim-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}
          done
        shell: bash

  e2e-test:
    needs: [get-version, dockerize]
    uses: ./.github/workflows/cypress-e2e-parallelization.yml
    with:
      name: e2e
      module_name: centreon
      image_name: centreon-web
      features_path: tests/e2e/cypress/e2e
      major_version: ${{ needs.get-version.outputs.major_version }}
      package_cache_key: ${{ github.sha }}-${{ github.run_id }}-rpm-el9
      package_directory: centreon/tests/e2e/cypress/fixtures/rpms
    secrets:
      registry_username: ${{ secrets.DOCKER_REGISTRY_ID }}
      registry_password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}
